config/routes.rb
Rails.application.routes.draw do
  resources :actors
  resources :actor_movies
  resources :movies
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/actor.rb
class Actor < ApplicationRecord
end

app/models/actor_movie.rb
class ActorMovie < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
end

app/controllers/actor_movies_controller.rb
class ActorMoviesController < ApplicationController
  before_action :set_actor_movie, only: %i[ show edit update destroy ]

  # GET /actor_movies or /actor_movies.json
  def index
    @actor_movies = ActorMovie.all
  end

  # GET /actor_movies/1 or /actor_movies/1.json
  def show
  end

  # GET /actor_movies/new
  def new
    @actor_movie = ActorMovie.new
  end

  # GET /actor_movies/1/edit
  def edit
  end

  # POST /actor_movies or /actor_movies.json
  def create
    @actor_movie = ActorMovie.new(actor_movie_params)

    respond_to do |format|
      if @actor_movie.save
        format.html { redirect_to @actor_movie, notice: "Actor movie was successfully created." }
        format.json { render :show, status: :created, location: @actor_movie }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @actor_movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /actor_movies/1 or /actor_movies/1.json
  def update
    respond_to do |format|
      if @actor_movie.update(actor_movie_params)
        format.html { redirect_to @actor_movie, notice: "Actor movie was successfully updated." }
        format.json { render :show, status: :ok, location: @actor_movie }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @actor_movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /actor_movies/1 or /actor_movies/1.json
  def destroy
    @actor_movie.destroy
    respond_to do |format|
      format.html { redirect_to actor_movies_url, notice: "Actor movie was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_actor_movie
      @actor_movie = ActorMovie.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def actor_movie_params
      params.require(:actor_movie).permit(:actor_id, :name)
    end
end

app/controllers/actors_controller.rb
class ActorsController < ApplicationController
  before_action :set_actor, only: %i[ show edit update destroy ]

  # GET /actors or /actors.json
  def index
    @actors = Actor.all
  end

  # GET /actors/1 or /actors/1.json
  def show
  end

  # GET /actors/new
  def new
    @actor = Actor.new
  end

  # GET /actors/1/edit
  def edit
  end

  # POST /actors or /actors.json
  def create
    @actor = Actor.new(actor_params)

    respond_to do |format|
      if @actor.save
        format.html { redirect_to @actor, notice: "Actor was successfully created." }
        format.json { render :show, status: :created, location: @actor }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @actor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /actors/1 or /actors/1.json
  def update
    respond_to do |format|
      if @actor.update(actor_params)
        format.html { redirect_to @actor, notice: "Actor was successfully updated." }
        format.json { render :show, status: :ok, location: @actor }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @actor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /actors/1 or /actors/1.json
  def destroy
    @actor.destroy
    respond_to do |format|
      format.html { redirect_to actors_url, notice: "Actor was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_actor
      @actor = Actor.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def actor_params
      params.require(:actor).permit(:id, :name)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: %i[ show edit update destroy ]

  # GET /movies or /movies.json
  def index
    @movies = Movie.all
  end

  # GET /movies/1 or /movies/1.json
  def show
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies or /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: "Movie was successfully created." }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1 or /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: "Movie was successfully updated." }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1 or /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: "Movie was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def movie_params
      params.require(:movie).permit(:movie_name)
    end
end

app/helpers/actor_movies_helper.rb
module ActorMoviesHelper
end

app/helpers/actors_helper.rb
module ActorsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/actor_movies/_form.html.erb
<%= form_with(model: actor_movie, local: true) do |form| %>
  <% if actor_movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(actor_movie.errors.count, "error") %> prohibited this actor_movie from being saved:</h2>

      <ul>
        <% actor_movie.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :actor_id %>
    <%= form.number_field :actor_id %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/actor_movies/edit.html.erb
<h1>Editing Actor Movie</h1>

<%= render 'form', actor_movie: @actor_movie %>

<%= link_to 'Show', @actor_movie %> |
<%= link_to 'Back', actor_movies_path %>

app/views/actor_movies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Actor Movies</h1>

<table>
  <thead>
    <tr>
      <th>Actor</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @actor_movies.each do |actor_movie| %>
      <tr>
        <td><%= actor_movie.actor_id %></td>
        <td><%= actor_movie.name %></td>
        <td><%= link_to 'Show', actor_movie %></td>
        <td><%= link_to 'Edit', edit_actor_movie_path(actor_movie) %></td>
        <td><%= link_to 'Destroy', actor_movie, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Actor Movie', new_actor_movie_path %>

app/views/actor_movies/new.html.erb
<h1>New Actor Movie</h1>

<%= render 'form', actor_movie: @actor_movie %>

<%= link_to 'Back', actor_movies_path %>

app/views/actor_movies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Actor:</strong>
  <%= @actor_movie.actor_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @actor_movie.name %>
</p>

<%= link_to 'Edit', edit_actor_movie_path(@actor_movie) %> |
<%= link_to 'Back', actor_movies_path %>

app/views/actors/_form.html.erb
<%= form_with(model: actor, local: true) do |form| %>
  <% if actor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(actor.errors.count, "error") %> prohibited this actor from being saved:</h2>

      <ul>
        <% actor.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :id %>
    <%= form.number_field :id %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/actors/edit.html.erb
<h1>Editing Actor</h1>

<%= render 'form', actor: @actor %>

<%= link_to 'Show', @actor %> |
<%= link_to 'Back', actors_path %>

app/views/actors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Actors</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @actors.each do |actor| %>
      <tr>
        <td><%= actor.id %></td>
        <td><%= actor.name %></td>
        <td><%= link_to 'Show', actor %></td>
        <td><%= link_to 'Edit', edit_actor_path(actor) %></td>
        <td><%= link_to 'Destroy', actor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Actor', new_actor_path %>

app/views/actors/new.html.erb
<h1>New Actor</h1>

<%= render 'form', actor: @actor %>

<%= link_to 'Back', actors_path %>

app/views/actors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @actor.id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @actor.name %>
</p>

<%= link_to 'Edit', edit_actor_path(@actor) %> |
<%= link_to 'Back', actors_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Homework</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/movies/_form.html.erb
<%= form_with(model: movie, local: true) do |form| %>
  <% if movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
        <% movie.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :movie_name %>
    <%= form.text_field :movie_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/movies/edit.html.erb
<h1>Editing Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

app/views/movies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Movies</h1>

<table>
  <thead>
    <tr>
      <th>Movie name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @movies.each do |movie| %>
      <tr>
        <td><%= movie.movie_name %></td>
        <td><%= link_to 'Show', movie %></td>
        <td><%= link_to 'Edit', edit_movie_path(movie) %></td>
        <td><%= link_to 'Destroy', movie, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Movie', new_movie_path %>

app/views/movies/new.html.erb
<h1>New Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Back', movies_path %>

app/views/movies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Movie name:</strong>
  <%= @movie.movie_name %>
</p>

<%= link_to 'Edit', edit_movie_path(@movie) %> |
<%= link_to 'Back', movies_path %>